const KNOWLEDGE_BASE = {
  munnar: {
    center: { lat: 10.089, lng: 77.059 },
    attractions: [
      {
        id: 'munnar-eravikulam',
        name: 'Eravikulam National Park',
        category: 'nature',
        description: 'High-altitude park known for the Nilgiri Tahr and sweeping views.',
        address: 'Eravikulam, Munnar, Kerala',
        location: { lat: 10.12, lng: 77.06 },
        openingHours: '8:00 AM - 4:00 PM',
        entryFeeUSD: 5,
        timeNeeded: '3-4 hours',
        rating: 4.8,
        totalReviews: 3000,
        bestTime: 'Morning',
        tips: 'Book the park slot early and carry light layers.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      },
      {
        id: 'munnar-kundala',
        name: 'Kundala Lake',
        category: 'nature',
        description: 'A serene lake surrounded by tea plantations and rolling hills.',
        address: 'Kundala, Munnar, Kerala',
        location: { lat: 10.23, lng: 77.12 },
        openingHours: 'Open all day',
        entryFeeUSD: 0,
        timeNeeded: '2 hours',
        rating: 4.6,
        totalReviews: 1800,
        bestTime: 'Late afternoon',
        tips: 'Great for boating and photography.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      },
    ],
    restaurants: [
      {
        id: 'munnar-rang-mahal',
        name: 'Rang Mahal',
        cuisine: 'North Indian',
        neighborhood: 'Munnar Town',
        type: 'Fine Dining',
        priceRange: '$$',
        rating: 4.5,
        mustOrder: 'Kerala Parotta',
        localFavorite: true,
        location: { lat: 10.088, lng: 77.063 },
        address: 'Munnar Town, Kerala',
        verified: true,
      },
      {
        id: 'munnar-mountain-cafe',
        name: 'Mountain View Cafe',
        cuisine: 'Continental',
        neighborhood: 'Munnar Town',
        type: 'Cafe',
        priceRange: '$',
        rating: 4.4,
        mustOrder: 'Tea and homemade cakes',
        localFavorite: true,
        location: { lat: 10.087, lng: 77.061 },
        address: 'Munnar Town, Kerala',
        verified: true,
      },
    ],
    hotels: [
      {
        id: 'munnar-hillview',
        name: 'Hotel Hillview',
        neighborhood: 'Munnar Town',
        stars: 3,
        pricePerNight: 70,
        totalPrice: 210,
        description: 'Comfortable stay close to the main town and viewpoints.',
        amenities: ['Free WiFi', 'Restaurant', 'Parking'],
        bookingTip: 'Book early on weekends.',
        type: 'Mid-Range',
        recommended: true,
      },
      {
        id: 'munnar-tea-resort',
        name: 'Tea Valley Resort',
        neighborhood: 'Munnar',
        stars: 4,
        pricePerNight: 120,
        totalPrice: 360,
        description: 'A scenic resort nestled in tea estates with good views.',
        amenities: ['Spa', 'Mountain View', 'Breakfast'],
        bookingTip: 'Ideal for couples and longer stays.',
        type: 'Resort',
        recommended: true,
      },
    ],
    guides: [
      {
        id: 'munnar-guide-1',
        name: 'Asha Thomas',
        bio: 'Local guide specializing in nature trails, tea gardens, and photography.',
        languages: ['English', 'Malayalam', 'Hindi'],
        specialties: ['Nature', 'Tea Estate Tours', 'Photography'],
        experience: 9,
        rating: 4.9,
        totalReviews: 180,
        price: 65,
        preferredGroupSize: '1-4 people',
        availability: true,
        certifications: ['Certified Tourism Guide'],
        compatibilityScore: 95,
        matchReason: 'Excellent for nature-focused travelers.',
      },
    ],
    safety: {
      destination: 'Munnar',
      overallSafetyRating: 8,
      safetyTier: 'Very Safe',
      travelAdvisory: { level: 1, message: 'Exercise normal precautions and respect local traffic rules.', issuedBy: 'Local Knowledge Base', lastUpdated: new Date().toISOString() },
      emergencyNumbers: [{ service: 'Emergency', number: '112', available: '24/7', notes: 'General emergency' }],
      safetyTips: { general: ['Keep valuables secure in crowded areas'], forWomen: ['Prefer well-lit routes at night'], forSoloTravelers: ['Share your route with someone'], nightSafety: ['Use registered taxis after dark'] },
      commonScams: [{ scam: 'Overpriced taxi rides', howToAvoid: 'Use official taxis or app-based rides' }],
      healthInfo: { waterSafety: 'Drink bottled or filtered water', foodSafety: 'Eat at busy restaurants', recommendedVaccines: ['No special vaccine required for most travelers'], healthRisks: ['High altitude weather changes'], nearestHospitalType: 'District Hospital', medicalStandard: 'Good' },
      culturalDos: ['Respect local religious spaces'],
      culturalDonts: ['Do not litter in protected areas'],
      localLaws: ['Carry ID if requested'],
      safeNeighborhoods: ['Munnar Town', 'Kundala'],
      areasToAvoid: ['Remote forest trails without a guide'],
      transportSafety: { recommendedTransport: ['Registered taxis', 'Private cars'], avoidTransport: ['Unlicensed rides'], taxiTips: 'Use official taxi stands or pre-booked transport' },
      weatherRisks: 'Check weather before visiting hill areas',
      embassyInfo: { note: 'Keep your embassy contacts handy' },
    },
  },
  delhi: {
    center: { lat: 28.6139, lng: 77.2090 },
    attractions: [
      {
        id: 'delhi-red-fort',
        name: 'Red Fort',
        category: 'historical',
        description: 'Historic Mughal fort that tells the story of imperial Delhi.',
        address: 'Netaji Subhash Marg, Delhi',
        location: { lat: 28.6562, lng: 77.2410 },
        openingHours: '9:30 AM - 4:30 PM',
        entryFeeUSD: 3,
        timeNeeded: '3 hours',
        rating: 4.7,
        totalReviews: 15000,
        bestTime: 'Morning',
        tips: 'Arrive early to avoid traffic and heat.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      },
    ],
    restaurants: [
      {
        id: 'delhi-bukhara',
        name: 'Bukhara',
        cuisine: 'North Indian',
        neighborhood: 'Maurya Sheraton',
        type: 'Fine Dining',
        priceRange: '$$$',
        rating: 4.7,
        mustOrder: 'Dal Bukhara',
        localFavorite: true,
        location: { lat: 28.6192, lng: 77.2192 },
        address: 'Maurya Sheraton, Delhi',
        verified: true,
      },
    ],
    hotels: [
      {
        id: 'delhi-maurya',
        name: 'The Maurya',
        neighborhood: 'Chanakyapuri',
        stars: 5,
        pricePerNight: 220,
        totalPrice: 660,
        description: 'Classic luxury hotel with easy access to key attractions.',
        amenities: ['Pool', 'Spa', 'Airport Transfer'],
        bookingTip: 'Reserve well in advance for Delhi events.',
        type: 'Luxury',
        recommended: true,
      },
    ],
    guides: [
      {
        id: 'delhi-guide-1',
        name: 'Ravi Sharma',
        bio: 'Expert guide for Old Delhi street food, monuments, and history.',
        languages: ['English', 'Hindi'],
        specialties: ['History', 'Food', 'Markets'],
        experience: 12,
        rating: 4.8,
        totalReviews: 220,
        price: 55,
        preferredGroupSize: '2-6 people',
        availability: true,
        certifications: ['Certified Local Guide'],
        compatibilityScore: 93,
        matchReason: 'Great for heritage-focused trips.',
      },
    ],
    safety: {
      destination: 'Delhi',
      overallSafetyRating: 5,
      safetyTier: 'Exercise Caution',
      travelAdvisory: { level: 2, message: 'Stay alert in crowded transit areas and avoid isolated routes at night.', issuedBy: 'Local Knowledge Base', lastUpdated: new Date().toISOString() },
      emergencyNumbers: [{ service: 'Emergency', number: '112', available: '24/7', notes: 'General emergency' }],
      safetyTips: { general: ['Keep your phone charged and your belongings close'], forWomen: ['Avoid poorly lit streets after dark'], forSoloTravelers: ['Use rideshare in the evening'], nightSafety: ['Stay in well-lit busy areas'] },
      commonScams: [{ scam: 'Taxi overcharging', howToAvoid: 'Use meter apps or official taxis' }],
      healthInfo: { waterSafety: 'Prefer bottled water', foodSafety: 'Choose busy, reputable eateries', recommendedVaccines: ['Routine vaccines'], healthRisks: ['Air pollution'], nearestHospitalType: 'Multi-specialty Hospital', medicalStandard: 'Good' },
      culturalDos: ['Respect local customs and dress modestly at religious sites'],
      culturalDonts: ['Do not photograph people without permission'],
      localLaws: ['Carry ID in public spaces'],
      safeNeighborhoods: ['Connaught Place', 'Chanakyapuri'],
      areasToAvoid: ['Isolated, poorly lit lanes at night'],
      transportSafety: { recommendedTransport: ['Metro', 'App-based cabs'], avoidTransport: ['Unlicensed taxis'], taxiTips: 'Plan routes in advance during rush hour' },
      weatherRisks: 'Expect heat and air pollution during summer',
      embassyInfo: { note: 'Keep your embassy contacts handy' },
    },
  },
  kochi: {
    center: { lat: 9.9312, lng: 76.2673 },
    attractions: [
      {
        id: 'kochi-chinese-nets',
        name: 'Chinese Fishing Nets',
        category: 'historical',
        description: 'Iconic cantilevered fishing nets along Fort Kochi beach, dating back to 14th century.',
        address: 'Fort Kochi, Kochi, Kerala',
        location: { lat: 9.9674, lng: 76.2427 },
        openingHours: 'Open all day',
        entryFeeUSD: 0,
        timeNeeded: '1-2 hours',
        rating: 4.6,
        totalReviews: 8500,
        bestTime: 'Sunset',
        tips: 'Visit during sunset for stunning silhouette photography.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      },
      {
        id: 'kochi-mattancherry-palace',
        name: 'Mattancherry Palace (Dutch Palace)',
        category: 'historical',
        description: 'Portuguese-built palace famous for exquisite Hindu temple murals and royal artifacts.',
        address: 'Palace Road, Mattancherry, Kochi',
        location: { lat: 9.9585, lng: 76.2595 },
        openingHours: '9:45 AM - 5:00 PM (Closed Fridays)',
        entryFeeUSD: 1,
        timeNeeded: '2 hours',
        rating: 4.5,
        totalReviews: 6200,
        bestTime: 'Morning',
        tips: 'Photography inside the mural room is restricted.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      },
      {
        id: 'kochi-jew-town',
        name: 'Jew Town & Paradesi Synagogue',
        category: 'historical',
        description: 'Charming historic quarter known for antique shops, spice markets, and the 1568 Paradesi Synagogue.',
        address: 'Jew Town, Mattancherry, Kochi',
        location: { lat: 9.9576, lng: 76.2598 },
        openingHours: '10:00 AM - 5:00 PM',
        entryFeeUSD: 1,
        timeNeeded: '2 hours',
        rating: 4.7,
        totalReviews: 5400,
        bestTime: 'Afternoon',
        tips: 'Explore local spice warehouses for authentic cardamom and pepper.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      },
      {
        id: 'kochi-st-francis',
        name: 'St. Francis Church',
        category: 'historical',
        description: 'One of the oldest European churches in India, originally the burial place of Vasco da Gama.',
        address: 'Headquarter Road, Fort Kochi, Kochi',
        location: { lat: 9.9660, lng: 76.2415 },
        openingHours: '7:00 AM - 6:30 PM',
        entryFeeUSD: 0,
        timeNeeded: '1 hour',
        rating: 4.4,
        totalReviews: 4100,
        bestTime: 'Morning',
        tips: 'Combine with a walking tour of Fort Kochi heritage streets.',
        mustSee: false,
        familyFriendly: true,
        verified: true,
      }
    ],
    restaurants: [
      {
        id: 'kochi-kassan',
        name: 'Oceanos Seafood Restaurant',
        cuisine: 'Kerala Seafood',
        neighborhood: 'Fort Kochi',
        type: 'Casual Dining',
        priceRange: '$$',
        rating: 4.6,
        mustOrder: 'Kerala Fish Curry Meals',
        localFavorite: true,
        location: { lat: 9.9650, lng: 76.2430 },
        address: 'Elphinstone Road, Fort Kochi',
        verified: true,
      },
      {
        id: 'kochi-kashi',
        name: 'Kashi Art Café',
        cuisine: 'Café & Bakery',
        neighborhood: 'Fort Kochi',
        type: 'Café',
        priceRange: '$$',
        rating: 4.7,
        mustOrder: 'Chocolate Cake & Cold Brew',
        localFavorite: true,
        location: { lat: 9.9645, lng: 76.2420 },
        address: 'Burgher Street, Fort Kochi',
        verified: true,
      }
    ],
    hotels: [
      {
        id: 'kochi-brunton',
        name: 'Brunton Boatyard - CGH Earth',
        neighborhood: 'Fort Kochi',
        stars: 5,
        pricePerNight: 240,
        totalPrice: 720,
        description: 'Restored Victorian shipyard hotel overlooking the harbour.',
        amenities: ['Harbour View Pool', 'Ayurvedic Spa', 'Seafood Restaurant'],
        bookingTip: 'Book sea-facing rooms for harbour views.',
        type: 'Luxury Heritage',
        recommended: true,
      }
    ],
    guides: [
      {
        id: 'kochi-guide-1',
        name: 'Joseph Menon',
        bio: 'Licensed heritage guide specializing in Fort Kochi history, spice trades, and art.',
        languages: ['English', 'Malayalam', 'Hindi'],
        specialties: ['Heritage Walks', 'Spice Trade History', 'Art & Biennales'],
        experience: 11,
        rating: 4.9,
        totalReviews: 195,
        price: 50,
        preferredGroupSize: '1-6 people',
        availability: true,
        certifications: ['Kerala Tourism Certified Guide'],
        compatibilityScore: 96,
        matchReason: 'Expert in Kochi colonial heritage.',
      }
    ],
    safety: {
      destination: 'Kochi',
      overallSafetyRating: 9,
      safetyTier: 'Very Safe',
      travelAdvisory: { level: 1, message: 'Normal safety precautions recommended in Kochi.', issuedBy: 'Local Knowledge Base', lastUpdated: new Date().toISOString() },
      emergencyNumbers: [{ service: 'Emergency', number: '112', available: '24/7', notes: 'General emergency' }],
      safetyTips: { general: ['Keep belongings secure in tourist spots'], forWomen: ['Safe for solo female travelers'], forSoloTravelers: ['Use registered autorickshaws'], nightSafety: ['Fort Kochi streets are pleasant and safe'] },
      commonScams: [{ scam: 'Overpriced fishing net tips', howToAvoid: 'Agree on small tip beforehand if fisherman demonstrates the net' }],
      healthInfo: { waterSafety: 'Prefer bottled or filtered water', foodSafety: 'Seafood at busy eateries is excellent', recommendedVaccines: ['Routine vaccines'], healthRisks: ['High humidity'], nearestHospitalType: 'General Hospital Kochi', medicalStandard: 'Excellent' },
      culturalDos: ['Dress respectfully when visiting synagogues and temples'],
      culturalDonts: ['Do not touch temple idols or sacred relics'],
      localLaws: ['Smoking in public places is restricted'],
      safeNeighborhoods: ['Fort Kochi', 'Mattancherry', 'Willingdon Island'],
      areasToAvoid: ['Isolated harbour docks late at night'],
      transportSafety: { recommendedTransport: ['Kochi Water Metro', 'Kochi Metro', 'Uber/Ola'], avoidTransport: ['Unmetered autos'], taxiTips: 'Water Metro is cheap and picturesque' },
      weatherRisks: 'Monsoon heavy rain from June to September',
      embassyInfo: { note: 'Consulates located in Chennai/Bangalore' },
    }
  },
  kolkata: {
    center: { lat: 22.5726, lng: 88.3639 },
    attractions: [
      {
        id: 'kolkata-victoria-memorial',
        name: 'Victoria Memorial',
        category: 'historical',
        description: 'Grand white marble building surrounded by lush gardens, dedicated to Queen Victoria.',
        address: 'Queens Way, Maidan, Kolkata',
        location: { lat: 22.5448, lng: 88.3426 },
        openingHours: '10:00 AM - 5:00 PM',
        entryFeeUSD: 2,
        timeNeeded: '2-3 hours',
        rating: 4.8,
        totalReviews: 24000,
        bestTime: 'Late afternoon',
        tips: 'Enjoy evening light and sound show in winter.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      },
      {
        id: 'kolkata-howrah-bridge',
        name: 'Howrah Bridge (Rabindra Setu)',
        category: 'architectural',
        description: 'Iconic balanced cantilever bridge over the Hooghly River, bustling day and night.',
        address: 'Howrah, Kolkata',
        location: { lat: 22.5851, lng: 88.3468 },
        openingHours: 'Open all day',
        entryFeeUSD: 0,
        timeNeeded: '1 hour',
        rating: 4.7,
        totalReviews: 31000,
        bestTime: 'Early morning',
        tips: 'Visit nearby Mullick Ghat Flower Market at sunrise.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      },
      {
        id: 'kolkata-dakshineswar',
        name: 'Dakshineswar Kali Temple',
        category: 'cultural',
        description: 'Revered Navaratna Hindu temple complex on the eastern bank of the Hooghly River.',
        address: 'Dakshineswar, Kolkata',
        location: { lat: 22.6547, lng: 88.3575 },
        openingHours: '6:00 AM - 12:30 PM, 3:00 PM - 8:30 PM',
        entryFeeUSD: 0,
        timeNeeded: '2 hours',
        rating: 4.8,
        totalReviews: 18000,
        bestTime: 'Morning',
        tips: 'Take the ferry across to Belur Math.',
        mustSee: true,
        familyFriendly: true,
        verified: true,
      }
    ],
    restaurants: [
      {
        id: 'kolkata-6-ballygunge',
        name: '6 Ballygunge Place',
        cuisine: 'Bengali Cuisine',
        neighborhood: 'Ballygunge',
        type: 'Fine Dining',
        priceRange: '$$',
        rating: 4.7,
        mustOrder: 'Koshi Mangsho & Daab Chingri',
        localFavorite: true,
        location: { lat: 22.5280, lng: 88.3650 },
        address: '6 Ballygunge Place, Kolkata',
        verified: true,
      },
      {
        id: 'kolkata-peter-cat',
        name: 'Peter Cat',
        cuisine: 'Continental & Indian',
        neighborhood: 'Park Street',
        type: 'Casual Dining',
        priceRange: '$$',
        rating: 4.6,
        mustOrder: 'Cheelo Kebab',
        localFavorite: true,
        location: { lat: 22.5530, lng: 88.3530 },
        address: 'Park Street, Kolkata',
        verified: true,
      }
    ],
    hotels: [
      {
        id: 'kolkata-oberoi-grand',
        name: 'The Oberoi Grand',
        neighborhood: 'Esplanade / Park Street',
        stars: 5,
        pricePerNight: 180,
        totalPrice: 540,
        description: 'Colonial-era luxury hotel known as the Grand Dame of Chowringhee.',
        amenities: ['Pool', 'Spa', 'Heritage Courtyard'],
        bookingTip: 'Ideal location for central Kolkata sightseeing.',
        type: 'Luxury Heritage',
        recommended: true,
      }
    ],
    guides: [
      {
        id: 'kolkata-guide-1',
        name: 'Subhashish Das',
        bio: 'Historian and author guiding cultural, literary, and culinary walks in Kolkata.',
        languages: ['English', 'Bengali', 'Hindi'],
        specialties: ['Colonial Architecture', 'Bengali Food', 'Literary History'],
        experience: 14,
        rating: 4.9,
        totalReviews: 210,
        price: 55,
        preferredGroupSize: '2-6 people',
        availability: true,
        certifications: ['West Bengal Tourism Guide'],
        compatibilityScore: 97,
        matchReason: 'Deep knowledge of Kolkata history.',
      }
    ],
    safety: {
      destination: 'Kolkata',
      overallSafetyRating: 8,
      safetyTier: 'Safe',
      travelAdvisory: { level: 1, message: 'Exercise normal safety precautions in Kolkata.', issuedBy: 'Local Knowledge Base', lastUpdated: new Date().toISOString() },
      emergencyNumbers: [{ service: 'Emergency', number: '112', available: '24/7', notes: 'General emergency' }],
      safetyTips: { general: ['Keep wallet secure in crowded markets'], forWomen: ['Use Metro or official yellow cabs'], forSoloTravelers: ['Friendly locals, safe for walking'], nightSafety: ['Park Street area remains lively late'] },
      commonScams: [{ scam: 'Touts near Howrah Station', howToAvoid: 'Use official prepaid taxi booth or app cabs' }],
      healthInfo: { waterSafety: 'Drink bottled water', foodSafety: 'Try legendary sweet shops like K.C. Das and Balaram Mullick', recommendedVaccines: ['Routine vaccines'], healthRisks: ['Humidity in summer'], nearestHospitalType: 'SSKM Hospital', medicalStandard: 'Good' },
      culturalDos: ['Remove shoes at temples and residential homes'],
      culturalDonts: ['Do not argue with street vendors aggressively'],
      localLaws: ['Plastic bags prohibited in heritage zones'],
      safeNeighborhoods: ['Park Street', 'Salt Lake', 'Ballygunge', 'New Town'],
      areasToAvoid: ['Red light areas around Sonagachi at night'],
      transportSafety: { recommendedTransport: ['Kolkata Metro', 'App cabs', 'Tram'], avoidTransport: ['Overcrowded buses'], taxiTips: 'Kolkata Metro is fast and air-conditioned' },
      weatherRisks: 'Monsoon street waterlogging during heavy downpours',
      embassyInfo: { note: 'US and UK Consulates located on Ho Chi Minh Sarani' },
    }
  }
};

function normalizeDestination(input) {
  return String(input || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function getDestinationKnowledge(destination) {
  const normalized = normalizeDestination(destination);
  if (!normalized) return null;

  const directMatch = KNOWLEDGE_BASE[normalized];
  if (directMatch) return directMatch;

  const matchKey = Object.keys(KNOWLEDGE_BASE).find((key) => normalized.includes(key) || key.includes(normalized));
  return matchKey ? KNOWLEDGE_BASE[matchKey] : null;
}
